#!/bin/sh

if [ -z "$1" ]; then

    echo mkpass username
    exit

fi

echo "$1" | sha1sum -b | sha512sum -b | uuencode -m - | tail -n+3 | head -1 | sed "s/^\(................................\).*/\1/"

